### ISSUE TITLE
Please update libheif to newer version

### ISSUE THREAD

**Issue by clement-lta** [catdad-experiments/heic-decode#8]
Hi @catdad 
I'm using heic-convert in a nodejs docker container. when I start my command. `docker-compose up`. it shows me this error bellow
![image](https://user-images.githubusercontent.com/59688529/93308859-063b7c80-f82d-11ea-9fba-96561fa57be3.png)
![image](https://user-images.githubusercontent.com/59688529/93308935-1ce1d380-f82d-11ea-82b9-50134b8677fc.png)

I'm using heic-convert version 1.2.3

Thanks

**Comment by catdad** [comment]
I don't think the actual error itself is in your screenshot. It looks like this is only part of a stacktrace as well as nodemon saying the app has crashed. What is the error message? Also, can you share any details that will help me reproduce the issue? How is this module being used? What image are you trying to convert? What version of node are you using? Do you have a code sample that I can run?
